export const DASHBOARD_COLUMNS = [
  ['CA', 'Midi Saisie', 'CA HT MIDI', 'bg-[#ffe699]'],
  ['CA', 'Soir Saisie', 'CA HT SOIR', 'bg-[#ffe699]'],
  ['CA', 'Limonade Saisie', 'CA HT LIMONADE', 'bg-[#ffe699]'],
  ['CA', 'TOTAL JOUR', 'CAHT JOUR', 'bg-[#ffe699]'],
  ['CA', 'CUMUL DEPUIS LE 01', 'CAHTCUMUL', 'bg-[#ffe699]'],
  ['CA', 'VAR % VS N-1', '', 'bg-hatched'],
  ['RESTAURANTS', 'MIDI\nPrevision Saisie', 'NB CVTS', 'bg-[#fff2cc]'],
  ['RESTAURANTS', 'MIDI\nPrevision Saisie', 'CVTS MOY HT', 'bg-[#fff2cc]'],
  ['RESTAURANTS', 'SOIR\nPrevision Saisie', 'NB CVTS', 'bg-[#fff2cc]'],
  ['RESTAURANTS', 'SOIR\nPrevision Saisie', 'CVTS MOY HT', 'bg-[#fff2cc]'],
  ['RESTAURANTS', 'JOUR\nPrevision Saisie', 'NB CVTS', 'bg-[#fff2cc]'],
  ['RESTAURANTS', 'JOUR\nPrevision Saisie', 'CVTS MOY HT', 'bg-[#fff2cc]'],
  ['RESTAURANTS', 'JOUR\nPrevision Saisie', 'CVTS CUMUL', 'bg-[#fff2cc]'],
  ['RESTAURANTS', 'VAR % VS N-1', '', 'bg-hatched'],
  ['LIMONADE', 'JOUR\nPrevision Saisie', 'NB CVTS', 'bg-[#fff2cc]'],
  ['LIMONADE', 'JOUR\nPrevision Saisie', 'CVTS MOY HT', 'bg-[#fff2cc]'],
  ['LIMONADE', 'VAR % VS N-1', '', 'bg-hatched'],
  ['REALISE', 'CA HT', 'VAE', 'bg-[#b4c6e7]'],
  ['REALISE', 'CA HT', 'MIDI', 'bg-[#b4c6e7]'],
  ['REALISE', 'CA HT', 'ECART AU\nBUDGET\nMIDI', 'bg-white'],
  ['REALISE', 'CA HT', 'SOIR', 'bg-[#b4c6e7]'],
  ['REALISE', 'CA HT', 'ECART AU\nBUDGET\nSOIR', 'bg-white'],
  ['REALISE', 'CA HT', 'LIMONADE', 'bg-[#b4c6e7]'],
  ['REALISE', 'CA HT', 'ECART AU\nBUDGET\nLIMONADE', 'bg-white'],
  ['REALISE', 'CA HT', 'TOTAL JOUR\nCAHT JOUR', 'bg-[#b4c6e7]'],
  ['REALISE', 'CA HT', 'ECART AU\nBUDGET\nJOUR', 'bg-white'],
  ['REALISE', 'CA HT', 'CUMUL\nDEPUIS LE 01\nCAHTCUMUL', 'bg-[#b4c6e7]'],
  ['REALISE', 'ECART AU BUDGET', 'JOUR', 'bg-white'],
  ['REALISE', 'ECART AU BUDGET', 'Depuis le 01', 'bg-white'],
  ['REALISE', 'ECART AU BUDGET', '% BUDGET', 'bg-white'],
  ['REALISE', 'TENDANCE\nMENSUEL', '', 'bg-white'],
  ['REALISE', 'TENDANCE\nVAR %\nVS N-1', '', 'bg-white'],
  ['REALISE', 'VAR %\nVS N-1', '', 'bg-hatched'],
  ['REALISE', 'COUVERTS RESTAURANT', 'MIDI\nNB CVTS', 'bg-[#b4c6e7]'],
  ['REALISE', 'COUVERTS RESTAURANT', 'MIDI\nCVTS MOY', 'bg-[#b4c6e7]'],
  ['REALISE', 'COUVERTS RESTAURANT', 'SOIR\nNB CVTS', 'bg-[#b4c6e7]'],
  ['REALISE', 'COUVERTS RESTAURANT', 'SOIR\nCVTS MOY', 'bg-[#b4c6e7]'],
  ['REALISE', 'COUVERTS RESTAURANT', 'JOUR\nNB CVTS', 'bg-[#b4c6e7]'],
  ['REALISE', 'COUVERTS RESTAURANT', 'JOUR\nCVTS MOY', 'bg-[#b4c6e7]'],
  ['REALISE', 'COUVERTS RESTAURANT', 'JOUR\nCVTS CUMUL', 'bg-[#b4c6e7]'],
  ['REALISE', 'COUVERTS RESTAURANT', 'Ecart au\nBudget\nCouverts SOIR', 'bg-[#fce4d6]'],
  ['REALISE', 'COUVERTS RESTAURANT', 'Ecart au\nBudget\nMOY CVTS SOIR', 'bg-[#fce4d6]'],
  ['REALISE', 'COUVERTS RESTAURANT', 'VAR %\nVS N-1', 'bg-hatched'],
  ['REALISE', 'COUVERTS LIMONADE', 'JOUR\nNB CVTS', 'bg-[#b4c6e7]'],
  ['REALISE', 'COUVERTS LIMONADE', 'JOUR\nCVTS MOY', 'bg-[#b4c6e7]'],
  ['REALISE', 'COUVERTS LIMONADE', 'JOUR\nCVTS CUMUL', 'bg-[#b4c6e7]'],
  ['REALISE', 'COUVERTS LIMONADE', 'Ecart au\nBudget\nCouverts', 'bg-white'],
  ['REALISE', 'COUVERTS LIMONADE', 'Ecart au\nBudget\nMoy CVTS', 'bg-white'],
  ['REALISE', 'COUVERTS LIMONADE', 'VAR %\nVS N-1', 'bg-hatched'],
  ['EVENEMENTS RESTAURANTS', 'EVENEMENTS RESTAURANTS', 'EVENEMENTS RESTAURANTS', 'bg-[#e9eef7]'],
  ['EVENEMENTS NATIONAL', 'EVENEMENTS NATIONAL', 'EVENEMENTS NATIONAL', 'bg-[#e2efda]'],
  ['DEMARQUES', 'PERSONNEL', '', 'bg-[#e2efda]'],
  ['DEMARQUES', 'Ratio\nPerso', '', 'bg-[#fce4d6]'],
  ['DEMARQUES', 'OPERATIONEL', '', 'bg-[#e2efda]'],
  ['DEMARQUES', 'Ratio Cuisine', '', 'bg-[#fce4d6]'],
  ['DEMARQUES', 'TOTAL', '', 'bg-[#e2efda]'],
  ['DEMARQUES', 'EXPLICATION DEMARQUE', '', 'bg-white'],
  ['COUT MATIERE', 'ACHATS LIQUIDE HT', 'C10', 'bg-[#e2efda]'],
  ['COUT MATIERE', 'ACHATS LIQUIDE HT', 'RICHARD VINS', 'bg-[#e2efda]'],
  ['COUT MATIERE', 'ACHATS LIQUIDE HT', 'CAFE RICHARD', 'bg-[#e2efda]'],
  ['COUT MATIERE', 'ACHATS LIQUIDE HT', 'STORIA', 'bg-[#e2efda]'],
  ['COUT MATIERE', 'ACHATS SOLIDES HT', 'BRAKE', 'bg-[#e2efda]'],
  ['COUT MATIERE', 'ACHATS SOLIDES HT', 'POMONA F&L', 'bg-[#e2efda]'],
  ['COUT MATIERE', 'ACHATS SOLIDES HT', 'SOCOPA', 'bg-[#e2efda]'],
  ['COUT MATIERE', 'ACHATS SOLIDES HT', 'EPISAVEUR', 'bg-[#e2efda]'],
  ['COUT MATIERE', 'ACHATS SOLIDES HT', 'MAMMAFIORE', 'bg-[#e2efda]'],
  ['COUT MATIERE', 'ACHATS SOLIDES HT', 'COMPAGNIE DES DESSERTS', 'bg-[#e2efda]'],
  ['COUT MATIERE', 'ACHATS SOLIDES HT', 'DISTRIPATE', 'bg-[#e2efda]'],
  ['COUT MATIERE', 'ACHATS SOLIDES HT', 'METRO /\nDEPANNAGE', 'bg-[#e2efda]'],
  ['COUT MATIERE', 'ACHATS SOLIDES HT', 'MARTEL', 'bg-[#e2efda]'],
  ['COUT MATIERE', 'ACHAT HT', 'TOTAL HT', 'bg-[#a9d08e]'],
  ['COUT MATIERE', 'ACHAT HT', 'CUMUL HT', 'bg-[#a9d08e]'],
  ['COUT MATIERE', 'RATIO', 'SANS LE\nSTOCK', 'bg-[#e2efda]'],
  ['FRAIS DE PERSONNEL PROJECTION', '', 'TOTAL HEURES\nTRAVAILLEES', 'bg-white'],
  ['FRAIS DE PERSONNEL PROJECTION', 'PROJECTION S/C', 'CADRE\nCUISINE\n38,54 €', 'bg-[#fce4d6]'],
  ['FRAIS DE PERSONNEL PROJECTION', 'PROJECTION S/C', 'CADRE\nSALLE\n38,54 €', 'bg-[#fce4d6]'],
  ['FRAIS DE PERSONNEL PROJECTION', 'PROJECTION S/C', 'MAITRISE\nCUISINE\n20,85 €', 'bg-[#fce4d6]'],
  ['FRAIS DE PERSONNEL PROJECTION', 'PROJECTION S/C', 'MAITRISE\nSALLE\n20,85 €', 'bg-[#fce4d6]'],
  ['FRAIS DE PERSONNEL PROJECTION', 'PROJECTION S/C', 'NIV I ET II\nCUISINE\n16,04 €', 'bg-[#fce4d6]'],
  ['FRAIS DE PERSONNEL PROJECTION', 'PROJECTION S/C', 'NIV I ET II\nSALLE\n16,04 €', 'bg-[#fce4d6]'],
  ['FRAIS DE PERSONNEL PROJECTION', 'PROJECTION S/C', 'NIV III\nCUISINE\n18,35 €', 'bg-[#fce4d6]'],
  ['FRAIS DE PERSONNEL PROJECTION', 'PROJECTION S/C', 'NIV III\nSALLE\n18,35 €', 'bg-[#fce4d6]'],
  ['FRAIS DE PERSONNEL PROJECTION', 'PROJECTION S/C', 'APPRENTI\nCUISINE\n8,39 €', 'bg-[#fce4d6]'],
  ['FRAIS DE PERSONNEL PROJECTION', 'PROJECTION S/C', 'APPRENTI\nSALLE\n8,39 €', 'bg-[#fce4d6]'],
  ['FRAIS DE PERSONNEL PROJECTION', '', 'COUT GLOBAL', 'bg-white'],
  ['FRAIS DE PERSONNEL PROJECTION', 'PRODUCTIVITE\nCIBLE\n50,00', 'PRODUCTIVITE\nREELLE', 'bg-white'],
  ['FRAIS DE PERSONNEL PROJECTION', 'BUDGET FRAIS\nPERSONNEL\n35,00%', 'FRAIS PERSONNEL\n%', 'bg-white'],
  ['FRAIS DE PERSONNEL PROJECTION', '', 'RATIO HEBDO %', 'bg-white'],
  ['FRAIS DE PERSONNEL REALISE', '', 'TOTAL HEURES\nTRAVAILLEES', 'bg-white'],
  ['FRAIS DE PERSONNEL REALISE', 'FRAIS PERSONNEL REALISE', 'CADRE\nCUISINE\n38,54 €', 'bg-[#fce4d6]'],
  ['FRAIS DE PERSONNEL REALISE', 'FRAIS PERSONNEL REALISE', 'CADRE\nSALLE\n38,54 €', 'bg-[#fce4d6]'],
  ['FRAIS DE PERSONNEL REALISE', 'FRAIS PERSONNEL REALISE', 'MAITRISE\nCUISINE\n20,85 €', 'bg-[#fce4d6]'],
  ['FRAIS DE PERSONNEL REALISE', 'FRAIS PERSONNEL REALISE', 'MAITRISE\nSALLE\n20,85 €', 'bg-[#fce4d6]'],
  ['FRAIS DE PERSONNEL REALISE', 'FRAIS PERSONNEL REALISE', 'NIV I ET II\nCUISINE\n16,04 €', 'bg-[#fce4d6]'],
  ['FRAIS DE PERSONNEL REALISE', 'FRAIS PERSONNEL REALISE', 'NIV I ET II\nSALLE\n16,04 €', 'bg-[#fce4d6]'],
  ['FRAIS DE PERSONNEL REALISE', 'FRAIS PERSONNEL REALISE', 'NIV III\nCUISINE\n18,35 €', 'bg-[#fce4d6]'],
  ['FRAIS DE PERSONNEL REALISE', 'FRAIS PERSONNEL REALISE', 'NIV III\nSALLE\n18,35 €', 'bg-[#fce4d6]'],
  ['FRAIS DE PERSONNEL REALISE', 'FRAIS PERSONNEL REALISE', 'APPRENT\nI CUISINE\n8,39 €', 'bg-[#fce4d6]'],
  ['FRAIS DE PERSONNEL REALISE', 'FRAIS PERSONNEL REALISE', 'APPRENT\nI SALLE\n8,39 €', 'bg-[#fce4d6]'],
  ['FRAIS DE PERSONNEL REALISE', '', 'COUT GLOBAL', 'bg-white'],
  ['FRAIS DE PERSONNEL REALISE', 'PRODUCTIVITE\nCIBLE\n50,00', 'PRODUCTIVITE\nREELLE', 'bg-white'],
  ['FRAIS DE PERSONNEL REALISE', 'BUDGET FRAIS\nPERSONNEL\n35,00%', 'FRAIS PERSONNEL\n%', 'bg-white'],
  ['FRAIS DE PERSONNEL REALISE', '', 'RATIO HEBDO %', 'bg-white'],
  ['FRAIS DE PERSONNEL REALISE', '', 'Ecart au Budget\nNB d\'Heure', 'bg-white'],
  ['FRAIS DE PERSONNEL REALISE', '', 'Ecart au budget\nS/C %', 'bg-white'],
  ['FRAIS DE PERSONNEL REALISE', '', 'VAR %\nVS N-1', 'bg-hatched'],
  ['FRAIS GENERAUX', 'ENTRETIEN ET REPARATION', 'DATE', 'bg-[#e9eef7]'],
  ['FRAIS GENERAUX', 'ENTRETIEN ET REPARATION', 'FOURNISSEUR', 'bg-[#e9eef7]'],
  ['FRAIS GENERAUX', 'ENTRETIEN ET REPARATION', 'MOTIF ACHAT', 'bg-[#e9eef7]'],
  ['FRAIS GENERAUX', 'ENTRETIEN ET REPARATION', 'MONTANT HT', 'bg-[#e9eef7]'],
  ['FRAIS GENERAUX', 'ECOLAB / DIVERSEY', 'DATE', 'bg-[#e9eef7]'],
  ['FRAIS GENERAUX', 'ECOLAB / DIVERSEY', 'FOURNISSEURS', 'bg-[#e9eef7]'],
  ['FRAIS GENERAUX', 'ECOLAB / DIVERSEY', 'MOTIF ACHAT', 'bg-[#e9eef7]'],
  ['FRAIS GENERAUX', 'ECOLAB / DIVERSEY', 'MONTANT HT', 'bg-[#e9eef7]'],
  ['FRAIS GENERAUX', 'MARKETING LOCAL (BFF / FUCHEY / TRADER)', 'DATE', 'bg-[#e9eef7]'],
  ['FRAIS GENERAUX', 'MARKETING LOCAL (BFF / FUCHEY / TRADER)', 'FOURNISSEURS', 'bg-[#e9eef7]'],
  ['FRAIS GENERAUX', 'MARKETING LOCAL (BFF / FUCHEY / TRADER)', 'MOTIF ACHAT', 'bg-[#e9eef7]'],
  ['FRAIS GENERAUX', 'MARKETING LOCAL (BFF / FUCHEY / TRADER)', 'MONTANT HT', 'bg-[#e9eef7]'],
  ['CONTRAT MENSUALISES', '', 'Nom', 'bg-[#e9eef7]'],
  ['CONTRAT MENSUALISES', '', 'Montant', 'bg-[#e9eef7]'],
  ['RESULTATS MENSUEL HT', 'CA / COUVERTS', 'Indicateur', 'bg-[#fff2cc]'],
  ['RESULTATS MENSUEL HT', 'CA / COUVERTS', 'Valeur', 'bg-white']
];

export const DAYS = ['dimanche', 'lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi'];
export const MONTH_NAMES = ['janvier', 'février', 'mars', 'avril', 'mai', 'juin', 'juillet', 'août', 'septembre', 'octobre', 'novembre', 'décembre'];

export const DASHBOARD_TABS = [
  { id: 'CA', label: 'CA & Couverts' },
  { id: 'REALISE', label: 'Réalisé & Événements' },
  { id: 'DEMARQUES', label: 'Démarques' },
  { id: 'COUT_MATIERE', label: 'Coût Matière' },
  { id: 'FRAIS_PERSONNEL', label: 'Frais de Personnel' },
  { id: 'FRAIS_GENERAUX', label: 'Frais Généraux' },
  { id: 'CONTRAT', label: 'Contrats' },
  { id: 'RESULTATS', label: 'Résultats Mensuels' },
];

export const EDITABLE_COLS = [
  6, 7, 8, 9, 14, 15,
  17, 18, 20, 22,
  49, 50,
  57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
  78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
  93, 94, 95, 96, 97, 98, 99, 100, 101, 102
];
